# Github sets these, and we can't change them.
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# These we can modify.
exclude:
  [Dockerfile, docker-compose.yml, .dockerignore, Gemfile.lock, Gemfile, vendor]
encoding: UTF-8
permalink: pretty

sass:
  sass_dir: css

defaults:
  - scope:
      path: ""
    values:
      extrajs: []
